name = "phoi"
main = "worker/index.js"
compatibility_date = "2024-05-28"

# 启用静态资源功能
[assets]
directory = "./dist"
binding = "ASSETS"

[env.production]
account_id = "your-account-id"
workers_dev = true
route = ""
zone_id = ""

[vars]
ENVIRONMENT = "production"